version: '2'
services:
  jenkins_server:
    build:  .
    privileged: true
    user: root
    ports: 
    - 8080:8080
    volumes:
    - /data/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - ./workspace:/var/jenkins_home/workspace/
    
  nexus:
    privileged: true
    user: root
    image: sonatype/nexus3
      

    volumes:
      
      - ./nexus-data:/nexus-data

    ports:
    - 8081:8081
    - 8084:8084



